/* Automatically generated by './build/build-entry.js' */
import './css/index.scss';
import './css/reset.css';
import croup from './directives/croup';

import Button from '../packages/button';
import IconBlock from '../packages/iconBlock';
import IconCircle from '../packages/iconCircle';
import IconDefault from '../packages/iconDefault';
import IconGreyBlock from '../packages/iconGreyBlock';
import MenuItem from '../packages/menuItem';
import RadioButton from '../packages/radioButton';
import RadioGroup from '../packages/radioGroup';
import ToolItem from '../packages/toolItem';

const components = [
    Button,
    IconBlock,
    IconCircle,
    IconDefault,
    IconGreyBlock,
    MenuItem,
    RadioButton,
    RadioGroup,
    ToolItem
];

const install = function(Vue, opts = {}) {
    components.map(component => {
        Vue.component(component.name, component);
    });

    Vue.directive('croup', croup);
};

if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

let calico = {
    version: '0.1.0',
    install,
    Button,
    IconBlock,
    IconCircle,
    IconDefault,
    IconGreyBlock,
    MenuItem,
    RadioButton,
    RadioGroup,
    ToolItem
};

export default calico