/* Automatically generated by './build/build-entry.js' */
import './css/index.scss';
import './css/reset.css';

import croup from './directives/croup';
import blur from './directives/blur';

import Aside from '../packages/aside';
import Button from '../packages/button';
import ColorOption from '../packages/colorOption';
import ColorSelect from '../packages/colorSelect';
import Header from '../packages/header';
import IconBlock from '../packages/iconBlock';
import IconCircle from '../packages/iconCircle';
import IconDefault from '../packages/iconDefault';
import IconGreyBlock from '../packages/iconGreyBlock';
import LineOption from '../packages/lineOption';
import LineSelect from '../packages/lineSelect';
import Main from '../packages/main';
import MenuItem from '../packages/menuItem';
import Message from '../packages/message';
import Option from '../packages/option';
import Pagination from '../packages/pagination';
import RadioButton from '../packages/radioButton';
import RadioGroup from '../packages/radioGroup';
import Row from '../packages/row';
import Select from '../packages/select';
import Switch from '../packages/switch';
import ToolItem from '../packages/toolItem';

const components = [
    Aside,
    Button,
    ColorOption,
    ColorSelect,
    Header,
    IconBlock,
    IconCircle,
    IconDefault,
    IconGreyBlock,
    LineOption,
    LineSelect,
    Main,
    MenuItem,
    Option,
    Pagination,
    RadioButton,
    RadioGroup,
    Row,
    Select,
    Switch,
    ToolItem
];

const install = function(Vue, opts = {}) {
    components.map(component => {
        Vue.component(component.name, component);
    });
    Vue.use(Message);
    Vue.directive('croup', croup);
    Vue.directive('blur', blur);
};

if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

let calico = {
    version: '0.1.0',
    install,
    Aside,
    Button,
    ColorOption,
    ColorSelect,
    Header,
    IconBlock,
    IconCircle,
    IconDefault,
    IconGreyBlock,
    LineOption,
    LineSelect,
    Main,
    MenuItem,
    Option,
    Pagination,
    RadioButton,
    RadioGroup,
    Row,
    Select,
    Switch,
    ToolItem
};

export default calico